#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Cloudflare R2 setup for Recipe Images"

# ── 1. The bucket ─────────────────────────────────────────────────────────
stage "Cloudflare: create the bucket"
say "Recipe Images live in one R2 bucket. Uploads go straight from the phone"
say "to it, and the API only signs and records (docs/adr/0006)."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Click 'Create bucket'."
step "Name it (bitely-images is the obvious choice) and pick a location."
step "Leave the default storage class, then click 'Create bucket'."
ask R2_BUCKET "Bucket name:"
write_env R2_BUCKET "$R2_BUCKET"

# ── 2. The account id ─────────────────────────────────────────────────────
stage "Cloudflare: the account id"
say "Presigned uploads address <account-id>.r2.cloudflarestorage.com. They"
say "work on neither the Public Development URL nor a custom domain, so this"
say "hostname is the write path no matter what the read path becomes."
step "On the R2 overview page, find the S3 API endpoint in the right sidebar:"
note "  https://<account-id>.r2.cloudflarestorage.com"
step "Copy the account id out of it (the part before .r2)."
ask R2_ACCOUNT_ID "Account id:"
write_env R2_ACCOUNT_ID "$R2_ACCOUNT_ID"

# ── 3. The read path ──────────────────────────────────────────────────────
stage "Cloudflare: enable the Public Development URL"
say "The corpus is public, so Recipe Images are read straight from the bucket."
warn "r2.dev is rate limited by Cloudflare and not meant for production traffic."
note "It costs one environment variable to move to a custom domain later."
open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/$R2_BUCKET/settings"
step "Find 'Public Development URL' (older dashboards say 'R2.dev subdomain')."
step "Click Enable, then confirm by typing 'allow'."
step "Copy the URL it shows: https://pub-<hash>.r2.dev"
ask R2_PUBLIC_BASE_URL "Public Development URL:"
write_env R2_PUBLIC_BASE_URL "$R2_PUBLIC_BASE_URL"

# ── 4. The lifecycle rule ─────────────────────────────────────────────────
stage "Cloudflare: expire abandoned uploads"
say "Uploads are signed into incoming/ and promoted when the Recipe is shared."
say "Whatever is abandoned or rejected is left for this rule, which is why the"
say "API has no reaper job."
open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/$R2_BUCKET/settings"
step "Find 'Object lifecycle rules' and click 'Add rule'."
step "Name it something like 'expire-incoming'."
step "Scope it to the prefix: incoming/"
step "Action: delete uploaded objects 1 day after upload."
step "Save the rule."
pause "Rule saved?"

# ── 5. The token ──────────────────────────────────────────────────────────
stage "Cloudflare: mint the API token"
warn "Scope matters here: Object Read & Write on this one bucket, not Admin."
say "The API's credentials can write objects and nothing else — it cannot"
say "create, configure or delete a bucket."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Click 'Create API token' (an Account API token, not a User one)."
step "Permissions: 'Object Read & Write'."
step "Specify bucket(s): select $R2_BUCKET only."
step "Leave the TTL as forever unless you plan to rotate it."
step "Create the token, then copy the two S3 credentials it shows once."
ask R2_ACCESS_KEY_ID "Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Secret Access Key:"
write_env R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
write_env R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── 6. Render ─────────────────────────────────────────────────────────────
stage "Render: the five environment variables"
say "The API refuses to boot without all five, rather than serving image URLs"
say "that point at nothing."
open_url "https://dashboard.render.com/"
step "Open the bitelyapi service, then 'Environment'."
step "Add each of these, then 'Save changes' (the service redeploys):"
note "  R2_ACCOUNT_ID        = $R2_ACCOUNT_ID"
note "  R2_BUCKET            = $R2_BUCKET"
note "  R2_PUBLIC_BASE_URL   = $R2_PUBLIC_BASE_URL"
note "  R2_ACCESS_KEY_ID     = $R2_ACCESS_KEY_ID"
note "  R2_SECRET_ACCESS_KEY = (the secret you pasted; it is in $ENV_FILE)"
pause "All five saved?"
# ──────────────────────────────────────────────────────────────────────────

finish
